// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaEfdtq2C3MB3Cy7PGDcODb4doqSdWw-E',
    appId: '1:474577649316:web:e8a2c70cde62398f4ef031',
    messagingSenderId: '474577649316',
    projectId: 'gonder-gelsin-cf201',
    authDomain: 'gonder-gelsin-cf201.firebaseapp.com',
    storageBucket: 'gonder-gelsin-cf201.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SV-62aTQ8XJruFn4A5k9DlR6Un43Nec',
    appId: '1:474577649316:android:286e11a4751e86574ef031',
    messagingSenderId: '474577649316',
    projectId: 'gonder-gelsin-cf201',
    storageBucket: 'gonder-gelsin-cf201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0MfscSYA_Zh0Iq1wxlWzoc9vjbAb1qs',
    appId: '1:474577649316:ios:ac485715c696bd304ef031',
    messagingSenderId: '474577649316',
    projectId: 'gonder-gelsin-cf201',
    storageBucket: 'gonder-gelsin-cf201.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ0MfscSYA_Zh0Iq1wxlWzoc9vjbAb1qs',
    appId: '1:474577649316:ios:ac485715c696bd304ef031',
    messagingSenderId: '474577649316',
    projectId: 'gonder-gelsin-cf201',
    storageBucket: 'gonder-gelsin-cf201.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaEfdtq2C3MB3Cy7PGDcODb4doqSdWw-E',
    appId: '1:474577649316:web:a424b48812ec0fa34ef031',
    messagingSenderId: '474577649316',
    projectId: 'gonder-gelsin-cf201',
    authDomain: 'gonder-gelsin-cf201.firebaseapp.com',
    storageBucket: 'gonder-gelsin-cf201.appspot.com',
  );
}
