// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_cmdPc75PIeTeDl3okbYh8eLydaGZrLc',
    appId: '1:1078539395990:web:fce9ce041f7bc9871cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    authDomain: 'gonder-gelsin-mobile.firebaseapp.com',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    measurementId: 'G-LYBTC8KQT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVs3izAzZtob4hnVf1IoDqlZS6GRJvAUU',
    appId: '1:197601339687:android:b6470da296e7c09fdb2102',
    messagingSenderId: '197601339687',
    projectId: 'gondergelsin-mobile-app',
    databaseURL: 'https://gondergelsin-mobile-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gondergelsin-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1CWKiJC3Nky_gy7SrSRH9KAvS02xCoM',
    appId: '1:197601339687:ios:4efd557d6d0952eddb2102',
    messagingSenderId: '197601339687',
    projectId: 'gondergelsin-mobile-app',
    databaseURL: 'https://gondergelsin-mobile-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gondergelsin-mobile-app.appspot.com',
    iosClientId: '197601339687-rjfo1vmb04i1hdsch5jvroh15ksrg5k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gondergelsinMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBikhJUL4QsxU8VCopVFgIxIqpTZTCmAg',
    appId: '1:1078539395990:ios:cc572652b0ac14811cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDynjBXNZ1j9DxqOmCGUhbX4liDeF-vruY',
    appId: '1:197601339687:web:ded20019ffb3bd5ddb2102',
    messagingSenderId: '197601339687',
    projectId: 'gondergelsin-mobile-app',
    authDomain: 'gondergelsin-mobile-app.firebaseapp.com',
    databaseURL: 'https://gondergelsin-mobile-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gondergelsin-mobile-app.appspot.com',
  );

}