// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_cmdPc75PIeTeDl3okbYh8eLydaGZrLc',
    appId: '1:1078539395990:web:fce9ce041f7bc9871cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    authDomain: 'gonder-gelsin-mobile.firebaseapp.com',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    measurementId: 'G-LYBTC8KQT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxrGwGaN9hDOfyNULBfEJrfc7fByImIM',
    appId: '1:1078539395990:android:f12b9f915bb2c01c1cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBikhJUL4QsxU8VCopVFgIxIqpTZTCmAg',
    appId: '1:1078539395990:ios:cc572652b0ac14811cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBikhJUL4QsxU8VCopVFgIxIqpTZTCmAg',
    appId: '1:1078539395990:ios:cc572652b0ac14811cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_cmdPc75PIeTeDl3okbYh8eLydaGZrLc',
    appId: '1:1078539395990:web:40538e07e7bd9c0d1cf3b7',
    messagingSenderId: '1078539395990',
    projectId: 'gonder-gelsin-mobile',
    authDomain: 'gonder-gelsin-mobile.firebaseapp.com',
    storageBucket: 'gonder-gelsin-mobile.appspot.com',
    measurementId: 'G-LG6MTX2SCX',
  );

}